In [1]:
from google.colab import drive
drive.mount('/content/drive')
%cd '/content/drive/MyDrive/Python ile Makine Öğrenmesi/Ders 4 - Çoklu Doğrusal Regresyon (Multiple Linear Regression)'
!ls

Mounted at /content/drive
/content/drive/MyDrive/Python ile Makine Öğrenmesi/Ders 4 - Çoklu Doğrusal Regresyon (Multiple Linear Regression)
'Multiple Linear Regression.ipynb'   Ödev.ipynb   odev_tenis.csv   veriler.csv


In [2]:
import numpy as np
import pandas as pd

In [5]:
veriler = pd.read_csv("odev_tenis.csv")
veriler

outlook  temperature  humidity  windy play
0      sunny           85        85  False   no
1      sunny           80        90   True   no
2   overcast           83        86  False  yes
3      rainy           70        96  False  yes
4      rainy           68        80  False  yes
5      rainy           65        70   True   no
6   overcast           64        65   True  yes
7      sunny           72        95  False   no
8      sunny           69        70  False  yes
9      rainy           75        80  False  yes
10     sunny           75        70   True  yes
11  overcast           72        90   True  yes
12  overcast           81        75  False  yes
13     rainy           71        91   True   no

# Veri Hazırlama

In [50]:
outlook = veriler.iloc[:, 0:1].values
windy = veriler.iloc[:, 3:4].values
play = veriler.iloc[:, 4:].values


In [51]:
from sklearn import preprocessing

le = preprocessing.LabelEncoder()

outlook[:,0] = le.fit_transform(outlook)
play[:,0] = le.fit_transform(play)

outlook

/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_label.py:116: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_label.py:116: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([[2],
       [2],
       [0],
       [1],
       [1],
       [1],
       [0],
       [2],
       [2],
       [1],
       [2],
       [0],
       [0],
       [1]], dtype=object)

In [53]:
ohe = preprocessing.OneHotEncoder()

outlook = ohe.fit_transform(outlook).toarray()
play = ohe.fit_transform(play).toarray()

df = pd.DataFrame(windy, columns=['windy'])
df_encoded = pd.get_dummies(df['windy'], prefix='windy')
windy_encoded = df_encoded.values

In [55]:
windy_encoded

array([[1, 0],
       [0, 1],
       [1, 0],
       [1, 0],
       [1, 0],
       [0, 1],
       [0, 1],
       [1, 0],
       [1, 0],
       [1, 0],
       [0, 1],
       [0, 1],
       [1, 0],
       [0, 1]], dtype=uint8)

In [56]:
sonuc1 = pd.DataFrame(outlook, columns=["overcast", "rainy", "sunny"])
sonuc2 = pd.DataFrame(play[:,0], columns=["play"])
sonuc3 = pd.DataFrame(windy_encoded[:,0], columns=["windy"])

In [67]:
temperature = veriler[["temperature"]]
humidity = veriler[["humidity"]]

In [68]:
s = pd.concat([sonuc1, sonuc2], axis=1)
s2 = pd.concat([s, sonuc3], axis=1)
s3 = pd.concat([s2, temperature], axis=1)
s4 = pd.concat([s3, humidity], axis=1)

In [69]:
s4

overcast  rainy  sunny  play  windy  temperature  humidity
0        0.0    0.0    1.0   1.0      1           85        85
1        0.0    0.0    1.0   1.0      0           80        90
2        1.0    0.0    0.0   0.0      1           83        86
3        0.0    1.0    0.0   0.0      1           70        96
4        0.0    1.0    0.0   0.0      1           68        80
5        0.0    1.0    0.0   1.0      0           65        70
6        1.0    0.0    0.0   0.0      0           64        65
7        0.0    0.0    1.0   1.0      1           72        95
8        0.0    0.0    1.0   0.0      1           69        70
9        0.0    1.0    0.0   0.0      1           75        80
10       0.0    0.0    1.0   0.0      0           75        70
11       1.0    0.0    0.0   0.0      0           72        90
12       1.0    0.0    0.0   0.0      1           81        75
13       0.0    1.0    0.0   1.0      0           71        91

# Model Oluşturma

In [78]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

x_train, x_test, y_train, y_test = train_test_split(s3, humidity, test_size=0.33, random_state=0)
model = LinearRegression()
model.fit(x_train, y_train)

y_pred = model.predict(x_test)
y_pred

array([[84.45365573],
       [63.93839954],
       [85.76050662],
       [64.21013241],
       [75.06793322]])

In [79]:
y_test

humidity
8         70
6         65
4         80
11        90
2         86

# Geri yayılım ile eleme

In [80]:
import statsmodels.api as sm

X = np.append(arr = np.ones((14,1)).astype(int), values=s3, axis=1)
X

array([[ 1.,  0.,  0.,  1.,  1.,  1., 85.],
       [ 1.,  0.,  0.,  1.,  1.,  0., 80.],
       [ 1.,  1.,  0.,  0.,  0.,  1., 83.],
       [ 1.,  0.,  1.,  0.,  0.,  1., 70.],
       [ 1.,  0.,  1.,  0.,  0.,  1., 68.],
       [ 1.,  0.,  1.,  0.,  1.,  0., 65.],
       [ 1.,  1.,  0.,  0.,  0.,  0., 64.],
       [ 1.,  0.,  0.,  1.,  1.,  1., 72.],
       [ 1.,  0.,  0.,  1.,  0.,  1., 69.],
       [ 1.,  0.,  1.,  0.,  0.,  1., 75.],
       [ 1.,  0.,  0.,  1.,  0.,  0., 75.],
       [ 1.,  1.,  0.,  0.,  0.,  0., 72.],
       [ 1.,  1.,  0.,  0.,  0.,  1., 81.],
       [ 1.,  0.,  1.,  0.,  1.,  0., 71.]])

In [82]:
X_l = s3.iloc[:, [0,1,2,3,4,5]].values
X_l = np.array(X_l, dtype=float)
model = sm.OLS(humidity, X_l).fit()
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:               humidity   R-squared:                       0.294
Model:                            OLS   Adj. R-squared:                 -0.148
Method:                 Least Squares   F-statistic:                    0.6653
Date:                Sun, 02 Jul 2023   Prob (F-statistic):              0.661
Time:                        11:45:40   Log-Likelihood:                -49.542
No. Observations:                  14   AIC:                             111.1
Df Residuals:                       8   BIC:                             114.9
Df Model:                           5                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
x1            40.0826     43.513      0.921      0.384     -60.258     140.424
x2            43.3273     39.282      1.103      0.302     -47.257     133.911
x3            37.1226     42.705      0.869      0.410     -61.356     135.601
x4             8.2778      8.029      1.031      0.333     -10.237      26.793
x5             4.0286      7.229      0.557      0.593     -12.641      20.698
x6             0.4920      0.597      0.825      0.433      -0.884       1.868
==============================================================================
Omnibus:                        0.935   Durbin-Watson:                   2.416
Prob(Omnibus):                  0.627   Jarque-Bera (JB):                0.823
Skew:                           0.389   Prob(JB):                        0.663
Kurtosis:                       2.103   Cond. No.                     1.81e+03
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.81e+03. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [87]:
X_l = s3.iloc[:, [5]].values
X_l = np.array(X_l, dtype=float)
model = sm.OLS(humidity, X_l).fit()
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                                 OLS Regression Results                                
=======================================================================================
Dep. Variable:               humidity   R-squared (uncentered):                   0.985
Model:                            OLS   Adj. R-squared (uncentered):              0.984
Method:                 Least Squares   F-statistic:                              835.6
Date:                Sun, 02 Jul 2023   Prob (F-statistic):                    3.49e-13
Time:                        11:46:55   Log-Likelihood:                         -52.350
No. Observations:                  14   AIC:                                      106.7
Df Residuals:                      13   BIC:                                      107.3
Df Model:                           1                                                  
Covariance Type:            nonrobust                                                  
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
x1             1.1052      0.038     28.908      0.000       1.023       1.188
==============================================================================
Omnibus:                        1.445   Durbin-Watson:                   2.713
Prob(Omnibus):                  0.485   Jarque-Bera (JB):                0.983
Skew:                           0.363   Prob(JB):                        0.612
Kurtosis:                       1.923   Cond. No.                         1.00
==============================================================================

Notes:
[1] R² is computed without centering (uncentered) since the model does not contain a constant.
[2] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""